USE bic3tab;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS change_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(320) NOT NULL,
    changed_at DATETIME(6) NOT NULL,
    BICCPTCLI_OLD CHAR(8) NOT NULL,
    BICVCLI_OLD DECIMAL(5,0) NOT NULL,
    SHEMAIL2DE_OLD CHAR(1) NULL,
    BICSNIF_OLD CHAR(9) NULL,
    BICSCCC_OLD CHAR(11) NULL,
    BICSPRACA_OLD CHAR(2) NULL,
    BICSSERV_OLD CHAR(3) NULL,
    BICSPROD_OLD CHAR(3) NULL,
    BICCPTCLI_NEW CHAR(8) NOT NULL,
    BICVCLI_NEW DECIMAL(5,0) NOT NULL,
    SHEMAIL2DE_NEW CHAR(1) NULL,
    BICSNIF_NEW CHAR(9) NULL,
    BICSCCC_NEW CHAR(11) NULL,
    BICSPRACA_NEW CHAR(2) NULL,
    BICSSERV_NEW CHAR(3) NULL,
    BICSPROD_NEW CHAR(3) NULL,
    PRIMARY KEY (id),
    KEY ix_change_log_username (username),
    KEY ix_change_log_changed_at (changed_at),
    KEY ix_change_log_biccptcli (BICCPTCLI_OLD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
